spring.application.name=gym-analytics-api

# Conexión a Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.xiggoajtomuwtbarjtvj
spring.datasource.password=wawfiW-warqij-9sedne

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase API Settings
supabase.url=https://xiggoajtomuwtbarjtvj.supabase.co
# Anon Key (clave publica para el SDK de Flutter en el frontend)
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZ2dvYWp0b211d3RiYXJqdHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNDExODUsImV4cCI6MjA4NTcxNzE4NX0.SXg1cMSbqGHJ4fwSe5q9a_QQLQlYjsLcGLWLZauppbg
# JWT Secret (clave SECRETA para validar firmas de tokens de usuario)
# Obtenerlo en: Supabase Dashboard > Project Settings > API > JWT Settings > JWT Secret
supabase.jwt-secret=sFPFUgb0Wadct/MNM8xaPfFMFKh9ktMmA8fZkmcpMGwFxsujvUAZtN5W35c7oR+7nodXtlNgv2cwbFDU3B1ZMA==
